# nixpacks.toml

[phases.install]
# Commands to install dependencies.
# This part seems to be working correctly.
cmds = ["pip install -r requirements.txt", "pip install gunicorn"]

[phases.start]
# The command to start the application.
# Double-check this line for typos.
startCmd = "gunicorn --bind 0.0.0.0:8000 app:app"