# nixpacks.toml

[phases.install]
# Commands to install dependencies.
cmds = ["pip install -r requirements.txt"]

[phases.start]
# The command to start the application.
cmds = ["gunicorn --bind 0.0.0.0:8000 app:app"]